name: "PR Test"
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  ubuntu-build-upload:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/jasonyang-ee/stm32-builder:Ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: BUILD
        run: build.sh

  pr-check:
    if: ${{ always() }}
    needs:
      - github-build
      - arch-build
      - alpine-build
      - ubuntu-build-upload
    runs-on: ubuntu-latest
    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}